[package]
name = "dparse"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["basic"]
basic-parser = []
basic-tokens = []
basic = ["basic-parser", "basic-tokens"]
backtrace = []
